### ISSUE TITLE
Carousel image for dashbaord

### ISSUE THREAD

**Issue by prafullmaru** [prafullmaru/ePanchayat#11]
Need help for UX expert here to prepare nice high resolution image to display on dashboard carousel.

Currently I have simple put-up blank image with text. This will be target area. Any better suggestion are welcome!
![image](https://github.com/prafullmaru/ePanchayat/assets/105120779/0d8107ff-9527-4afb-89e1-69538559f750)

**Comment by Samm2201** [comment]
I am available and can offer help to design a few images.

**Comment by Samm2201** [comment]
@prafullmaru Please verify these images 
![F93ADB70-0A0A-4925-B3F5-558315F4E6F3](https://github.com/prafullmaru/ePanchayat/assets/133785130/d45020fc-e3ab-4a59-8596-22ee5bb90b28)
![F4F973AA-DD84-4635-9F74-FDF84B574C7C](https://github.com/prafullmaru/ePanchayat/assets/133785130/e685adb5-6a60-4256-8965-32a40948ddcc)
![56FB5DA8-DF49-41D5-BEA7-4F7B0F8C5C6F](https://github.com/prafullmaru/ePanchayat/assets/133785130/45e0ce12-8b06-4001-abe3-cf1799e6cbd7)

**Comment by prafullmaru** [comment]
Images looks fine. However background color is not matching with primary theme color - #7C84EC.
Update text and let you raise pull request.

**Comment by prafullmaru** [comment]
Addressed by PR - https://github.com/prafullmaru/ePanchayat/pull/27
