### ISSUE TITLE
Footer is Missing 

### ISSUE THREAD

**Issue by gajananbhalerao** [prafullmaru/ePanchayat#14]
It's better to have quick links at footer, or at least some licensing and contributors info.

**Comment by prafullmaru** [comment]
As we have good top navigation, we would like to leave much usable space for end-user. Though it's nice to have.
@HarshulChavda - Will you please take care of this with minimal use of height?

**Comment by prafullmaru** [comment]
Addressed with PR - https://github.com/prafullmaru/ePanchayat/pull/16
