### ISSUE TITLE
 Need to improve README and Environment set-up

### ISSUE THREAD

**Issue by HarshulChavda** [prafullmaru/ePanchayat#17]
As project is growing we need to have clear steps to begin with environment set-up and also let we improve README with TechStack, Features listed etc.

**Comment by prafullmaru** [comment]
@HarshulChavda - Thank you for raising this issue! 😊 Your contribution is valuable to us! 😊

We already have one task in planned - #10 , Would you like to take this?

**Comment by HarshulChavda** [comment]
Yes, @prafullmaru I will take this.
Thanks

**Comment by prafullmaru** [comment]
@HarshulChavda  - Assigned original ticket to you and closing this one.
