### ISSUE TITLE
DB Maintenance scripts

### ISSUE THREAD

**Issue by mohandivraniya** [prafullmaru/ePanchayat#42]
We need a script to get list of tables on which we need to perform maintenance, like:
- Index rebuild, re-organize
- Update statistics
- Shrink

**Comment by RiteshKolhe** [comment]
Hi Prafull,
I am taking this task, will check and explore the details.

**Comment by prafullmaru** [comment]
@RiteshKolhe - Sure.

**Comment by RiteshKolhe** [comment]
Thanks, will take a look

**Comment by RiteshKolhe** [comment]
Hi Prafull,
I have prepared the DB scripts, It tested in Dev db and working as expected, Let me share the Pupp request, please get it reviewed and let us know your feedback.

**Comment by RiteshKolhe** [comment]
https://github.com/prafullmaru/ePanchayat/pull/46
Please check the PR and review and approve it
